#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script to take screenshots on Archcraft.

# file
time=$(date +"%Y-%m-%d@%I-%M-%S%p")
geometry=$(xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current')
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}.png"
border='0.322,0.585,0.886'

# Directory
if [[ ! -d "${dir}" ]]; then
  mkdir -p "${dir}"
fi

# notify and view screenshot
notify_view() {
  notify_cmd_shot='dunstify -u low -h string:x-dunst-stack-tag:obscreenshot -i /usr/share/archcraft/icons/dunst/picture.png'
  ${notify_cmd_shot} "Copied to clipboard."
  paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  if [[ -f "${dir}/${file}" ]]; then
    viewnior "${dir}/${file}"
    ${notify_cmd_shot} "Screenshot Saved."
  else
    ${notify_cmd_shot} "Screenshot Deleted."
  fi
}

# Copy screenshot to clipboard
copy_shot() {
  tee "${file}" | xclip -selection clipboard -t image/png
}

# countdown
countdown() {
  for sec in $(seq "$1" -1 1); do
    dunstify -t 1000 -h string:x-dunst-stack-tag:screenshottimer -i /usr/share/archcraft/icons/dunst/timer.png "Taking shot in : ${sec}"
    sleep 1
  done
}

# take shots
shotnow() {
  cd "${dir}" && sleep 0.5 && flameshot full -p "${file}" -c
  killall flameshot
  xclip -selection clipboard -t image/png -i "${file}"
  paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  viewnior "${dir}/${file}"
}

shot5() {
  countdown '5'
  sleep 1 && cd "${dir}" && flameshot full -p "${file}" -c
  killall flameshot
  xclip -selection clipboard -t image/png -i "${file}"
  paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  viewnior "${dir}/${file}"
}

shot10() {
  countdown '10'
  sleep 1 && cd "${dir}" && flameshot full -p "${file}" -c
  killall flameshot
  xclip -selection clipboard -t image/png -i "${file}"
  paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  viewnior "${dir}/${file}"
}

shotwin() {
  cd "${dir}" && maim -u -f png -i "$(xdotool getactivewindow)" | copy_shot
  notify_view
}

shotarea() {
  cd "${dir}" && flameshot gui -p "${file}" -c
  killall flameshot
  xclip -selection clipboard -t image/png -i "${file}"
  paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
  viewnior "${dir}/${file}"
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    shotnow
  elif [[ "$1" == '--opt2' ]]; then
    shotarea
  elif [[ "$1" == '--opt3' ]]; then
    shotwin
  elif [[ "$1" == '--opt4' ]]; then
    shot5
  elif [[ "$1" == '--opt5' ]]; then
    shot10
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
"${option_1}")
  run_cmd --opt1
  ;;
"${option_2}")
  run_cmd --opt2
  ;;
"${option_3}")
  run_cmd --opt3
  ;;
"${option_4}")
  run_cmd --opt4
  ;;
"${option_5}")
  run_cmd --opt5
  ;;
esac

exit 0
