#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="${HOME}/.config/openbox"
STYLE="default"
RASI="${DIR}/themes/${STYLE}/rofi/music.rasi"

# Theme Elements
status="$(spotifyctl status)"
if [[ -z "${status}" ]]; then
  prompt='Offline'
  mesg="Spotify is Offline"
else
  prompt="$(spotifyctl status --format '%artist%')"
  mesg="$(spotifyctl status --format "%artist%") :: $(spotifyctl status --format "%title%")"
fi

# Options
layout=$(cat "${RASI}" | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "${layout}" == 'NO' ]]; then
  if [[ ${status} == *"playing"* ]]; then
    option_1=" Pause"
  else
    option_1="  Play"
  fi
  option_2="  Stop"
  option_3="  Previous"
  option_4="  Next"
  option_5="  Repeat"
  option_6="  Random"
else
  if [[ ${status} == *"playing"* ]]; then
    option_1="  "
  else
    option_1="  "
  fi
  option_2="  "
  option_3="  "
  option_4="  "
  option_5="  "
  option_6="  "
fi

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "${prompt}" \
    -mesg "${mesg}" \
    "${active}" "${urgent}" \
    -markup-rows \
    -theme "${RASI}"
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "${option_1}\n${option_2}\n${option_3}\n${option_4}" | rofi_cmd
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    spotifyctl playpause
  elif [[ "$1" == '--opt2' ]]; then
    spotifyctl pause
  elif [[ "$1" == '--opt3' ]]; then
    spotifyctl previous
  elif [[ "$1" == '--opt4' ]]; then
    spotifyctl next
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
"${option_1}")
  run_cmd --opt1
  ;;
"${option_2}")
  run_cmd --opt2
  ;;
"${option_3}")
  run_cmd --opt3
  ;;
"${option_4}")
  run_cmd --opt4
  ;;
esac
