#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Network Executor For Tint2

ESSID="$(ip route get 1.1.1.1 | awk '{print $5;exit}')"

if [[ ! -z "$ESSID" ]]; then
	echo " $ESSID"
else
	echo ' Disconnected'
fi
