[core] # Active application settings.
active_store = 'test' # Store key used by default. Default: "default".

[preferences] # UI behavior preferences.
auto_refresh_interval_ms = 5000 # Refresh interval in ms. Default: 5000.

[generation] # Default pass generate options.
default_length = 16                      # Generated password length. Default: 25.
symbols = true                           # Include symbols by default. Default: true.
character_set = '[[:punct:]][[:alnum:]]' # Charset when symbols are enabled. Default: "[[:punct:]][[:alnum:]]".
character_set_no_symbols = '[[:alnum:]]' # Charset when symbols are disabled. Default: "[[:alnum:]]".
memorable = false                        # Use memorable passwords diceware.

[clipboard] # Clipboard behavior after copy.
clear_after_seconds = 45 # Clear clipboard after seconds. Default: 45.
selection = 'clipboard'  # X selection to use: clipboard, primary, secondary. Default: "clipboard".

[gpg] # Supported GPG-related pass defaults.
opts = [] # Extra GPG options passed to pass. Default: [].

[extensions] # pass extension support.
enabled = false # Enable pass extensions. Default: false.

[stores] # Configured password stores.

[stores.default] # Default store (default).
path = '~/.password-store' # Password store path. Default: "~/.password-store".

[stores.test] # Testing store
path = '~/.cache/pass-gui/.password-store'
