" DO NOT EDIT THIS FILE
" Add your own customizations in /etc/skel/.vim_runtime/my_configs.vim

set runtimepath+=/etc/skel/.vim_runtime

source /etc/skel/.vim_runtime/vimrcs/basic.vim
source /etc/skel/.vim_runtime/vimrcs/filetypes.vim
source /etc/skel/.vim_runtime/vimrcs/plugins_config.vim
source /etc/skel/.vim_runtime/vimrcs/extended.vim
try
  source /etc/skel/.vim_runtime/my_configs.vim
catch
endtry
