[colors.bright]
black = "0x50545B"
blue = "0x7AA2F7"
cyan = "0x7DCFFF"
green = "0x73DACA"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xB5BCC9"
yellow = "0xEFCA84"

[colors.normal]
black = "0x14141E"
blue = "0x4CA6E8"
cyan = "0x7DCFFF"
green = "0x35BF88"
magenta = "0xBB9AF7"
red = "0xF7768E"
white = "0xE6E6E8"
yellow = "0xDBAC66"

[colors.primary]
background = "0x0D1117"
foreground = "0xABB2BF"

[colors.cursor]
cursor = "0xABB2BF"
text = "0x14141E"
