theme = "github_dark"

[editor]
line-number = "relative"
auto-format = true
mouse = true
continue-comments = false
color-modes = true
completion-replace = true
true-color = true
bufferline = "always"
end-of-line-diagnostics = "hint"
clipboard-provider = "x-clip"
insert-final-newline = true
indent-heuristic = "tree-sitter"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# '<' = '>'

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 10

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"
prefix-len = 2
max-diagnostics = 2

[keys.normal."space"]
v = ":clipboard-paste-replace"
i = ":pipe shellharden --transform ''"

[keys.select."space"]
v = ":clipboard-paste-replace"
i = ":pipe shellharden --transform ''"

[keys.normal]
C-s = [":format", ":write"] # format and save
C-d = [
  "extend_to_line_bounds",
  "yank",
  "paste_before",
]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-down = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]

[keys.select]
C-s = [":format", ":write"] # format and save
C-d = [
  "extend_to_line_bounds",
  "yank",
  "paste_before",
]
A-up = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-down = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before",
]

[keys.insert]
j = { k = "normal_mode" }   # Maps `jk` to enter normal mode
k = { j = "select_mode" }   # Maps `kj` to enter visual mode
C-s = [":format", ":write"] # format and save
C-d = [
  "extend_to_line_bounds",
  "yank",
  "paste_before",
]

