theme = "github_dark"

[editor]
line-number = "relative"
auto-format = true
mouse = true
continue-comments = false
color-modes = true
completion-replace = true
true-color = true
bufferline = "always"
end-of-line-diagnostics = "hint"
clipboard-provider = "x-clip"
insert-final-newline = true
indent-heuristic = "tree-sitter"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.lsp]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
# '<' = '>'

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 10

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "disable"
prefix-len = 2
max-diagnostics = 2

[keys.normal."space"]
v = ":clipboard-paste-replace"

[keys.select."space"]
v = ":clipboard-paste-replace"

[keys.normal]
X = ["extend_line_above"]
C-s = [":format", ":write"] # format and save
C-d = ["extend_to_line_bounds", "yank", "paste_before"]
A-r = [":reload-all"]
C-r = [":config-reload"]
"C-," = [":config-open"]

# Move lines up and down
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before"]

# A world of difference!
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

# Undoing the 'd' + motion commands restores the selection which is annoying
u = ["undo", "collapse_selection"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode"]

[keys.select]
X = ["extend_line_above"]
C-s = [":format", ":write"] # format and save
C-d = ["extend_to_line_bounds", "yank", "paste_before"]
A-r = [":reload-all"]
C-r = [":config-reload"]
"C-," = [":config-open"]

# Move lines up and down
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before"]

i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.insert]
j = { k = "normal_mode" }                               # Maps `jk` to enter normal mode
k = { j = "select_mode" }                               # Maps `kj` to enter visual mode
C-s = [":format", ":write"]                             # format and save
C-d = ["extend_to_line_bounds", "yank", "paste_before"]

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "normal_mode"]
