# ---- C++ ---- #
[[language]]
name = "cpp"
formatter = { command = "astyle", args = ["--options=$ARTISTIC_STYLE_OPTIONS"] }

# ---- C ---- #
[[language]]
name = "c"
formatter = { command = "astyle", args = ["--options=$ARTISTIC_STYLE_OPTIONS"] }
