indent = { tab-width = 2, unit = "  " }

# ---- C++ ---- #
[[language]]
name = "cpp"
formatter = { command = "astyle" }

# ---- C ---- #
[[language]]
name = "c"
formatter = { command = "astyle" }

# ---- Json ---- #
[[language]]
name = "json"
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path",
  "file.json",
] }
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

# ---- Typescript ---- #
[[language]]
name = "typescript"
roots = ["package.json", "package-lock.json"]
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path",
  "file.ts",
] }
language-servers = [
  "biome",
  # { name = "typescript-language-server", except-features = [
  #   "format",
  # ] },

]

# ---- Javascript ---- #
[[language]]
name = "javascript"
roots = ["package.json", "package-lock.json"]
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path",
  "file.js",
] }
language-servers = [
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]

# ---- Tsx ---- #
[[language]]
name = "tsx"
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path",
  "file.tsx",
] }

# ---- Jsx ---- #
[[language]]
name = "jsx"
formatter = { command = "biome", args = [
  "check",
  "--fix",
  "--config-path",
  "/home/othman/.config/biome.jsonc",
  "--stdin-file-path",
  "file.jsx",
] }

# ---- Deno ---- #
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc"]
auto-format = false
language-servers = [
  "deno-lsp",
  "biome",
  # { name = "typescript-language-server", except-features = [
  #   "format",
  # ] },
]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc"]
auto-format = false
language-servers = [
  "deno-lsp",
  "biome",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]

[[language]]
name = "jsx"
roots = ["deno.json", "deno.jsonc"]
auto-format = false
language-servers = [
  "deno-lsp",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "vscode-html-language-server",
  "superhtml",
  "biome",
]

[[language]]
name = "tsx"
roots = ["deno.json", "deno.jsonc"]
auto-format = false
language-servers = [
  "deno-lsp",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "vscode-html-language-server",
  "superhtml",
  "biome",
]

# ---- Deno LSP ---- #
[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

# ---- Biome LSP ---- #
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

# ---- Rust---- #
[[language]]
name = "rust"
formatter = { command = "rustfmt", args = [
  "--config-path",
  "/home/othman/.config/rustfmt.toml",
] }
indent = { tab-width = 2, unit = "  " }

# ---- JSON ---- #
[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]
