#!/usr/bin/env bash

# ---- Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com> ---- #

# ---- Kill if already running ---- #
killall -9 xfsettingsd picom polybar dunst ksuperkey copyq ollama mpd xfce-polkit blueman-applet edges skippy-xd fcitx5 sxhkd

# ---- Restore Wallpaper ---- #
nitrogen --restore

# ---- xfce4-settings daemon ---- #
xfsettingsd &

# ---- Disable power management ---- #
# xfce4-power-manager &
(sleep 1 && xset s off && xset s noblank && xset -dpms) &

# ---- Start Compositing Manager ---- #
exec picom &

# ---- Start Spotify listener ---- #
systemctl --user start spotify-listener &

# ---- Launch Polybar or Tint2 ---- #
bash ~/.config/openbox/themes/launch-bar.sh

# ---- Notification Daemon ---- #
exec dunst &

# ---- Start Music Player Daemon ---- #
# exec mpd &

# ---- Launch Plank ---- #
exec plank &

# ---- Thunar Daemon ---- #
exec thunar --daemon &

# ---- Start copyq server ---- #
exec copyq &

# ---- Start the ollama server ---- #
# exec ollama serve &

# ---- Enable Super Keys For Menu ---- #
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# ---- Enable hotcorners using edges ---- #
edges --topleft "skippy-xd --toggle" &

# --- Start fcitx5 daemon --- #
# fcitx5 -d &

# --- sxhkd for shortcuts --- #
sxhkd &

# Start DBus if not already running ---- #
if [[ -z "${DBUS_SESSION_BUS_ADDRESS}" ]]; then
  eval "$(dbus-launch --sh-syntax)"
  export DBUS_SESSION_BUS_ADDRESS
  export DBUS_SESSION_BUS_PID
fi

# ---- polkit agent ---- #
if ! ps aux | rg -iq 'polkit'; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# Ensure D-Bus knows about the X11 session
if command -v dbus-update-activation-environment &>/dev/null; then
  dbus-update-activation-environment --systemd DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP=openbox &
fi

# Start portals
/usr/lib/xdg-desktop-portal &
/usr/lib/xdg-desktop-portal-gtk &

# Start mediactl for polybar
/home/othman/scripts/bin/mediactl &
